name: aave_v3_optimism 
description: aave v3 optimism indexer 
networks: 
  - id: 10
    start_block: 4300000
    contracts:
      - name: AaveOracle
        handler: ./src/EventHandlers.js
        address:
          - 0xD81eb3728a631871a7eBBaD631b5f424909f0c77
        events:
         - event: "AssetSourceUpdated(address indexed asset, address indexed source)"
           requiredEntities: 
             - name: "Assetsourceupdated" 
         - event: "FallbackOracleUpdated(address indexed fallbackOracle)"
           requiredEntities:
             - name: "Fallbackoracleupdated"
         - event: "BaseCurrencySet(address indexed baseCurrency, uint256 baseCurrencyUnit)"
           requiredEntities: 
             - name: "Basecurrencyset" 
      - name: Pool #PoolAddressesProviderRegistry
        handler: ./src/EventHandlers.js
        address:
         - 0x770ef9f4fe897e59daCc474EF11238303F9552b6
        events:
         - event: "AddressesProviderRegistered(address indexed addressesProvider, uint256 indexed id)"
           requiredEntities: 
            - name: "Addressesproviderregistered"
         - event: "AddressesProviderUnregistered(address indexed addressesProvider, uint256 indexed id)"
           requiredEntities: 
             - name: "Addressesproviderunregistered"
         - event: "OwnershipTransferred(address indexed previousOwner, address indexed newOwner)"
           requiredEntities: 
             - name: "Ownershiptransferred"
      - name: Rewards #RewardsController
        handler: ./src/EventHandlers.js
        address:
          - 0x929EC64c34a17401F460460D4B9390518E5B473e
        events:
         - event: "AssetConfigUpdated(address indexed asset, address indexed reward, uint256 oldEmission, uint256 newEmission, uint256 oldDistributionEnd, uint256 newDistributionEnd, uint256 assetIndex)"
           requiredEntities: 
             - name: "Assetconfigupdated"
         - event: "Accrued(address indexed asset, address indexed reward, address indexed user, uint256 assetIndex, uint256 userIndex, uint256 rewardsAccrued)"
           requiredEntities: 
              - name: "Accrued"
         - event: "RewardsClaimed(address indexed user, address indexed reward, address indexed to, address claimer, uint256 amount)"
           requiredEntities: 
             - name: "Rewardsclaimed"
         - event: "RewardOracleUpdated(address indexed reward, address indexed rewardOracle)"
           requiredEntities: 
            - name: "Rewardoracleupdated"
         - event: "EmissionManagerUpdated(address indexed oldEmissionManager, address indexed newEmissionManager)"
           requiredEntities: 
             - name: "Emissionmanagerupdated"
         - event: "ClaimerSet(address indexed user, address indexed claimer)"
           requiredEntities: 
             - name: "Claimerset"
         - event: "TransferStrategyInstalled(address indexed reward, address indexed transferStrategy)" 
           requiredEntities: 
             - name: "Transferstrategyinstalled"
